apiVersion: v1
kind: Service
metadata:
  name: python-ml-pytorch
  namespace: getwebstack
  labels:
    app: python-ml-pytorch
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: python-ml-pytorch
